/**
 * @brief Constants and configuration for view rendering
 * @author Marc S. Ressl
 * @modifiers:
 *          Agustin Valenzuela,
 *          Alex Petersen,
 *          Dylan Frigerio,
 *          Enzo Fernandez Rosas
 *
 * @copyright Copyright (c) 2023-2024
 */

#ifndef VIEW_CONSTANTS_H
#define VIEW_CONSTANTS_H

#include "../model.h"

#define GAME_NAME "EDAversi"

 // Window configuration
#define WINDOW_WIDTH 1280
#define WINDOW_HEIGHT 720

// Board rendering constants
#define SQUARE_SIZE 80
#define SQUARE_PADDING 1.5F
#define SQUARE_CONTENT_OFFSET (SQUARE_PADDING)
#define SQUARE_CONTENT_SIZE (SQUARE_SIZE - 2 * SQUARE_PADDING)

#define PIECE_CENTER (SQUARE_SIZE / 2)
#define PIECE_RADIUS (SQUARE_SIZE * 80 / 100 / 2)

#define BOARD_X 40
#define BOARD_Y 40
#define BOARD_CONTENT_SIZE (BOARD_SIZE * SQUARE_SIZE)

#define OUTERBORDER_X (BOARD_X - OUTERBORDER_PADDING)
#define OUTERBORDER_Y (BOARD_Y - OUTERBORDER_PADDING)
#define OUTERBORDER_PADDING 40
#define OUTERBORDER_WIDTH 10
#define OUTERBORDER_SIZE (BOARD_CONTENT_SIZE + 2 * OUTERBORDER_PADDING)

// Text rendering constants
#define TITLE_FONT_SIZE 72
#define SUBTITLE_FONT_SIZE 36
#define NORMAL_FONT_SIZE 24

// Info panel positioning
#define INFO_CENTERED_X (OUTERBORDER_SIZE + (WINDOW_WIDTH - OUTERBORDER_SIZE) / 2)

#define INFO_TITLE_Y (WINDOW_HEIGHT / 2)

#define INFO_WHITE_SCORE_Y (WINDOW_HEIGHT * 1 / 4 - SUBTITLE_FONT_SIZE / 2)
#define INFO_WHITE_TIME_Y (WINDOW_HEIGHT * 1 / 4 + SUBTITLE_FONT_SIZE / 2)

#define INFO_BLACK_SCORE_Y (WINDOW_HEIGHT * 3 / 4 - SUBTITLE_FONT_SIZE / 2)
#define INFO_BLACK_TIME_Y (WINDOW_HEIGHT * 3 / 4 + SUBTITLE_FONT_SIZE / 2)

// Button configuration
#define INFO_BUTTON_WIDTH 280
#define INFO_BUTTON_HEIGHT 64

#define INFO_PLAYBLACK_BUTTON_X INFO_CENTERED_X
#define INFO_PLAYBLACK_BUTTON_Y (WINDOW_HEIGHT * 1 / 8)

#define INFO_PLAYWHITE_BUTTON_X INFO_CENTERED_X
#define INFO_PLAYWHITE_BUTTON_Y (WINDOW_HEIGHT * 7 / 8)

// Main menu button positions (3 opciones principales)
#define MENU_BUTTON_X (WINDOW_WIDTH / 2)
#define MENU_BUTTON_SPACING 100
#define MENU_BUTTON_START_Y (WINDOW_HEIGHT / 2)

#define MENU_1V1_BUTTON_Y (MENU_BUTTON_START_Y)
#define MENU_1VAI_BUTTON_Y (MENU_BUTTON_START_Y + MENU_BUTTON_SPACING)
#define MENU_SETTINGS_BUTTON_Y (MENU_BUTTON_START_Y + MENU_BUTTON_SPACING * 2)

// AI Difficulty menu
#define DIFFICULTY_BUTTON_START_Y (WINDOW_HEIGHT / 3)
#define DIFFICULTY_BUTTON_SPACING 90
#define DIFFICULTY_BUTTON_Y(index) (DIFFICULTY_BUTTON_START_Y + (index) * DIFFICULTY_BUTTON_SPACING)

#define DIFFICULTY_BACK_BUTTON_X (WINDOW_WIDTH / 2 - 150)
#define DIFFICULTY_BACK_BUTTON_Y (WINDOW_HEIGHT - 100)
#define DIFFICULTY_CONFIRM_BUTTON_X (WINDOW_WIDTH / 2 + 150)
#define DIFFICULTY_CONFIRM_BUTTON_Y (WINDOW_HEIGHT - 100)

// Settings button (in-game)
#define SETTINGS_ICON_SIZE 40
#define SETTINGS_BUTTON_X (WINDOW_WIDTH - SETTINGS_ICON_SIZE)
#define SETTINGS_BUTTON_Y (SETTINGS_ICON_SIZE)

// Settings overlay
#define SETTINGS_OVERLAY_WIDTH 500
#define SETTINGS_OVERLAY_X ((WINDOW_WIDTH - SETTINGS_OVERLAY_WIDTH) / 2)
#define SETTINGS_ITEM_HEIGHT 90
#define SETTINGS_ITEM_WIDTH 400
#define SETTINGS_ITEM_X (SETTINGS_OVERLAY_X + (SETTINGS_OVERLAY_WIDTH - SETTINGS_ITEM_WIDTH) / 2)

// AI Settings menu buttons
#define AI_SETTINGS_OVERLAY_HEIGHT 600
#define AI_SETTINGS_OVERLAY_Y ((WINDOW_HEIGHT - AI_SETTINGS_OVERLAY_HEIGHT) / 2)
#define AI_SETTINGS_ITEM_START_Y (AI_SETTINGS_OVERLAY_Y + SETTINGS_ITEM_HEIGHT)

#define AI_SETTINGS_DIFFICULTY_Y (AI_SETTINGS_ITEM_START_Y)
#define AI_SETTINGS_NODE_LIMIT_Y (AI_SETTINGS_ITEM_START_Y + SETTINGS_ITEM_HEIGHT * 1.5)
#define AI_SETTINGS_CONFIRM_Y (AI_SETTINGS_ITEM_START_Y + SETTINGS_ITEM_HEIGHT * 2.5)
#define AI_SETTINGS_CLOSE_Y (AI_SETTINGS_ITEM_START_Y + SETTINGS_ITEM_HEIGHT * 3.5)
#define AI_SETTINGS_MAIN_MENU_Y (AI_SETTINGS_ITEM_START_Y + SETTINGS_ITEM_HEIGHT * 4.5)

// Settings menu buttons
#define SETTINGS_OVERLAY_HEIGHT 300
#define SETTINGS_OVERLAY_Y ((WINDOW_HEIGHT - SETTINGS_OVERLAY_HEIGHT) / 2)

#define SETTINGS_ITEM_WIDTH 400
#define SETTINGS_ITEM_X (SETTINGS_OVERLAY_X + (SETTINGS_OVERLAY_WIDTH - SETTINGS_ITEM_WIDTH) / 2)
#define SETTINGS_ITEM_START_Y (SETTINGS_OVERLAY_Y + 1.5 * SETTINGS_ITEM_HEIGHT)

#define SETTINGS_CLOSE_Y (SETTINGS_ITEM_START_Y)
#define SETTINGS_MAIN_MENU_Y (SETTINGS_ITEM_START_Y + SETTINGS_ITEM_HEIGHT)

// Slider configuration
#define SLIDER_WIDTH 300
#define SLIDER_HEIGHT 20
#define SLIDER_X (SETTINGS_OVERLAY_X + (SETTINGS_OVERLAY_WIDTH - SLIDER_WIDTH) / 2)
#define SLIDER_HANDLE_RADIUS 12
#define NODE_LIMIT_MIN 100
#define NODE_LIMIT_MAX 1000000


#endif // VIEW_CONSTANTS_H